name: pin
description: A micro web app framework
version: 0.1.0
homepage: https://github.com/lucas979797/pin

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
